apiVersion: v1
kind: Service
metadata:
  name: broker-middleware
spec:
  type: {{ .Values.service.type }}
  selector:
    app: broker-middleware
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5000
